model:
  name: SyntalNet
  args:
    ind_cls_heads: ["Engagement", "Lead"]
    grp_cls_heads: ["Synchrony", "Confidence", "Transition"]
    cls_head_type: "cosine"
    proto_warmup_epochs: 3
    mm_fusion_type: "concat_mlp"

dataset:
  args:
    root_dir: "./dataset"
    modalities: ["face", "pose", "video", "turns", "utterance", "sentiment", "prosody", "audio",]
  split:
    mode: "kfold"  # "kfold", "logo", "item", "group"
    n_folds: 5
    seed: 17
  stats_dir: "./configs/normalization_stats.yaml"
  cls_count_dir: "./configs/class_counts.yaml"

training:
  seed: 42
  num_workers: 4
  prefetch_factor: 4
  epochs: 100
  batch_size: 12
  val_batch_size: 12
  learning_rate: 3.e-4
  min_lr: 1.e-5
  warmup_ratio: 0.1
  weight_decay: 0.002
  scheduler: "cosine_decay"  # cosine_decay | one_cycle
  grad_clip: 1.
  accum_steps: 4
  log_interval: 0
  track_fusion_aux: False
  track_classifier_aux: False
  loss_type: "multiclass"
  amp: False
  cb_beta: 0.9995
  focal_gamma: 2.
  la_tau: 0.
  label_smoothing: 0.01
  val_interval: 10
  ckpt_interval: 10

logging:
  log_dir: ./logs/EXPT_GLRX_concat_mlp
  checkpoint_dir: ./checkpoints/EXPT_GLRX_concat_mlp
