model:
  name: SyntalNet
  args: {
    ind_cls_heads: ["Engagement", "Lead"],
    use_emb: True,
    use_feat: True,
    cls_head_type: "cosine",
  }

dataset:
  args:
    root_dir: "./dataset"
    modalities: ["face", "pose", "video", "turns", "utterance", "sentiment", "prosody", "audio",]
    label_type: "kernel"
  split:
    mode: "item"  # "item" or "group" based split
    ratio: 0.2    # train-val split ratio
    groups: []    # groups to hold out for val
    seed: 17
  stats_dir: "./configs/normalization_stats.yaml"
  cls_count_dir: "./configs/class_counts.yaml"

training:
  seed: 42
  num_workers: 4
  epochs: 100
  batch_size: 12
  val_batch_size: 12
  learning_rate: 3.e-4
  min_lr: 1.e-5
  warmup_ratio: 0.08
  weight_decay: 1.e-4
  scheduler: "cosine_decay"  # cosine_decay | one_cycle
  grad_clip: 1.0
  accum_steps: 3
  loss_type: "focal"
  amp: False
  cb_beta: 0.999
  focal_gamma: 2.0
  label_smoothing: 0.05
  val_interval: 1
  ckpt_interval: 10

logging:
  log_dir: ./logs/test
  checkpoint_dir: ./checkpoints/test
